In [ ]:
import numpy as np
from scipy.linalg import solve

In [ ]:
def gauss(A, b, x, n):

    L = np.tril(A)
    U = A - L
    for i in range(n):
        x = np.dot(np.linalg.inv(L), b - np.dot(U, x))
        print(x)
    return x


In [ ]:
A = np.squeeze(np.array([[6, 0,-1,0,0],[-3,3,0,0,0], [0,-1,9,0,0],[0,-1,-8,11,-2], [-3, -1,0,0,4]]))

print (A)
A.shape

In [42]:
b = np.squeeze(np.array([50,160,105,3,0]))
x = [1, 1, 1]
n = 100
print(b)


[  50.  160.  105.    3.    0.]


In [43]:
print("\n\ninit"),
print(x)
print("n")
x = gauss(A,b, x, n,)
print("\nSol "),
print(x)
print("Act "),
print("\n")



init
[1, 1, 1]
n


ValueError: shapes (5,5) and (3,) not aligned: 5 (dim 1) != 3 (dim 0)

In [21]:
print(np.tril(A))

[[ 6  0  0  0  0]
 [-3  3  0  0  0]
 [ 0 -1  9  0  0]
 [ 0 -1 -8 11  0]
 [-3 -1  0  0  4]]


In [22]:
print(A-np.tril(A))

[[ 0  0 -1  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0 -2]
 [ 0  0  0  0  0]]


In [23]:
print(np.linalg.inv(A))

[[ 0.16981132  0.00628931  0.01886792  0.          0.        ]
 [ 0.16981132  0.33962264  0.01886792  0.          0.        ]
 [ 0.01886792  0.03773585  0.11320755  0.          0.        ]
 [ 0.06003431  0.07461407  0.08747856  0.09090909  0.04545455]
 [ 0.16981132  0.08962264  0.01886792  0.          0.25      ]]
