In [191]:
import numpy as np
from scipy.linalg import solve

In [192]:
def gauss(q, w, c, n):

    L = np.tril(q)
    U = q - L
    for i in range(n):
        c = np.dot(np.linalg.inv(L), b - np.dot(U, c))
        print(c)
    return c


In [193]:
q = np.squeeze(np.array([[6, 0,-1,0,0],[-3,3,0,0,0], [0,-1,9,0,0],[0,-1,-8,11,-2], [-3, -1,0,0,4]]))

print (q)
q.shape

[[ 6  0 -1  0  0]
 [-3  3  0  0  0]
 [ 0 -1  9  0  0]
 [ 0 -1 -8 11 -2]
 [-3 -1  0  0  4]]


(5, 5)

In [194]:
w = np.squeeze(np.array([50,0,160,0,0]))
c = [1,1,1,1,1]
n = 20
print(w)


[ 50   0 160   0   0]


In [199]:
print("\n initial c's = [1,1,1,1,1]")
c = gauss(q,w,c, n,)
print("\nSol "),
print(c)
print("Actual")  
print ("  11.50943393, 11.50943393, 19.05660377, 16.99828473, 11.5094339")
print("\n")


 initial c's = [1,1,1,1,1]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.05660377  16.99828473  11.50943396]
[ 11.50943396  11.50943396  19.056

In [196]:
print(np.tril(q))

[[ 6  0  0  0  0]
 [-3  3  0  0  0]
 [ 0 -1  9  0  0]
 [ 0 -1 -8 11  0]
 [-3 -1  0  0  4]]


In [190]:
print(q-np.tril(q))

[[ 0  0 -1  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0 -2]
 [ 0  0  0  0  0]]


In [188]:
print(np.linalg.inv(q))

[[ 0.16981132  0.00628931  0.01886792  0.          0.        ]
 [ 0.16981132  0.33962264  0.01886792  0.          0.        ]
 [ 0.01886792  0.03773585  0.11320755  0.          0.        ]
 [ 0.06003431  0.07461407  0.08747856  0.09090909  0.04545455]
 [ 0.16981132  0.08962264  0.01886792  0.          0.25      ]]
